tools:
  external_code_coverage:
    timeout: "1200"
  php_code_sniffer:
    config:
      standard: "PSR2"
  php_cpd: false
  php_cs_fixer:
      config: { level: psr2 }
  php_hhvm: true
  php_sim: true
  sensiolabs_security_checker: true

filter:
  excluded_paths:
    - tests/*
